import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

/**
 * Banner added at the top of the generated bundle.
 * Provides basic info and points to the GitHub repository.
 */
const banner = `
/*
FundMentality - Obsidian Plugin
This is a generated/bundled file by ESBuild.
For source code, visit: https://github.com/<your-github-repo>/FundMentality
*/
`;

// Determine mode: development (watch) or production (minified)
const isProduction = process.argv[2] === "production";

// Entry point for the plugin
const entryPoint = ["core/main.ts"];

// Output file
const outFile = "dist/main.js";

const context = await esbuild.context({
    entryPoints: entryPoint,
    bundle: true,
    format: "cjs", // Obsidian requires CommonJS
    target: "es2022",
    sourcemap: isProduction ? false : "inline",
    treeShaking: true,
    minify: isProduction,
    outfile: outFile,
    banner: {
        js: banner,
    },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules, // Node built-in modules
    ],
    logLevel: "info",
});

// Production build: build once and exit
if (isProduction) {
    await context.rebuild();
    console.log(`Production build completed: ${outFile}`);
    process.exit(0);
} else {
    // Development build: watch for changes
    console.log(` Watching for changes (development mode)...`);
    await context.watch();
}
